serial_no: _337322074715
robot_name: ur3e
device_type: d435i  
reconnect_timeout: 20.0
wait_for_device_timeout: 1200.0
world_frame_id: world
display_images: true
enable_rgbd: true
enable_pointcloud: true
enable_sync: true
align_depth_enable: true 
enable_color: true
enable_depth: true
rgb_camera_profile: 640x480x15
depth_module_profile: 1280x720x15

# moveit2
moveit2:
    max_velocity: 0.5
    max_accn: 0.5

# launch params
queue_size: 10
use_rviz: true

# calibration
tcp_precalibration_pose: [0, 0, 0]
tcp_precalibration_pose_joint_config: [
  0.70528755073090858203,
  -0.47350782606606161422,
  0.44994588116413816493,
  -1.47881747521479545053,
  -1.55107410624736069501,
  6.27620399017160915862
]

# TF
# Pose in Euler coordinates ordered x, y, z, yaw, pitch, roll respectively.
d435i_pose: [-1.0795, 0.3048, 0.37465, 0.275, 0.0, -0.520715] # manual; height of table not included because the xacro places the ur's height at 0!
d435i_pose_aruco: [0.8978, 0.5440, 1.546085, 2.566620, 0.221805, -0.520715]

# Physical camera params
camera_height: 0.025
camera_length: 0.09
camera_depth: 0.025

intrinsic_params:
    accelerometer:
        scale_factor: 1.0
        bias: 0.0
    gyro:
        bias: 0.0
    depth:
        frame_rate: 90
        fov:
            hor: 87
            vert: 58
        resolution: 
            height: 720
            width: 1280
        principal_point:
            x: 636.720153808594
            y: 370.6181640625
        focal_length:
            x:  642.312133789062
            y:  642.312133789062
        distortion: brown_conrady
        window_size: [25, 350]
    rgbd:
        frame_rate: 30
        fov:
            hor: 69
            vert: 43.47
        resolution: 
            height: 720
            width: 1280
        principal_point:
            x: 643.51513671875
            y: 369.371307373047
        focal_length:
            x:  903.686645507812
            y:  902.850952148438
        distortion: inverse_brown_conrady
        window_size: [25, 75]

extrinsic_params:
    # experiment 
    vention_table_width: 1.092
    vention_table_height: 0.755
    camera_mount_bar_length: 0.2413
    camera_mount_height: 0.47625 # 0.778585
    clamp_offset: [0.1524, 0.03175]
    alp_to_cam_rpy: [0.69486183, 0.0, 0.0]
    mount_to_cam_xyz: [0.0398, 0.033175, 0.0125] 
    mount_to_cam_rpy: [0.6948618321360263, 0, 0]



    