model {
  file: "model.sdf"
}
name: "Cole_Hardware_Plant_Saucer_Brown_125"
description: "Cole Hardware Plant Saucer, Brown, 12.5\""
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Cole Hardware"
}
annotations {
  key: "gtin"
  value: "00047625126715"
}
annotations {
  key: "sku"
  value: "00047625126715"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
