services:
  lab-7-sim-docker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.sim
      args:
        userid: ${userid}
        groupid: ${groupid}
    image: lab-7-sim-image:latest
    container_name: lab-7-sim-container
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    # Required for communicating over the network
    network_mode: "host"
    ipc: "host"
    pid: "host"
    # Required for accessing hardware
    privileged: true
    tty: true
    stdin_open: true
    device_cgroup_rules:
      - 'c 81:* rmw'     
      - 'c 189:* rmw'   
    entrypoint: >
      bash -c "
        set -e;
        sudo udevadm control --reload-rules 2>/dev/null || true;
        sudo udevadm trigger 2>/dev/null || true;
        sudo chown -R ${userid}:${groupid} /home/robot/ros2_ws/src;
        exec bash"
