model {
  file: "model.sdf"
}
name: "Ecoforms_Plant_Container_S24Turquoise"
description: "Ecoforms Plant Container, S24-Turquoise"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Ecoforms"
}
annotations {
  key: "gtin"
  value: "00755866662410"
}
annotations {
  key: "sku"
  value: "00755866662410"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
